// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHPgIOjsLJEvmCn2xB1Megy8VxdAphjPs',
    appId: '1:376704236556:web:ba8b57ec2608f7c0924229',
    messagingSenderId: '376704236556',
    projectId: 'kkkt-miyuji',
    authDomain: 'kkkt-miyuji.firebaseapp.com',
    databaseURL: 'https://kkkt-miyuji-default-rtdb.firebaseio.com',
    storageBucket: 'kkkt-miyuji.firebasestorage.app',
    measurementId: 'G-4ZEV6PTTKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3uMY37SYP-DSzB4ECjmiLhZEPPJNRu7Y',
    appId: '1:376704236556:android:2c0612157d52db1d924229',
    messagingSenderId: '376704236556',
    projectId: 'kkkt-miyuji',
    databaseURL: 'https://kkkt-miyuji-default-rtdb.firebaseio.com',
    storageBucket: 'kkkt-miyuji.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr-tfHefMzDglbpV4zvMRH1lYbJnk03mk',
    appId: '1:376704236556:ios:2d869a6467250f51924229',
    messagingSenderId: '376704236556',
    projectId: 'kkkt-miyuji',
    databaseURL: 'https://kkkt-miyuji-default-rtdb.firebaseio.com',
    storageBucket: 'kkkt-miyuji.firebasestorage.app',
    iosBundleId: 'com.isofttz.kanisaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr-tfHefMzDglbpV4zvMRH1lYbJnk03mk',
    appId: '1:376704236556:ios:2d869a6467250f51924229',
    messagingSenderId: '376704236556',
    projectId: 'kkkt-miyuji',
    databaseURL: 'https://kkkt-miyuji-default-rtdb.firebaseio.com',
    storageBucket: 'kkkt-miyuji.firebasestorage.app',
    iosBundleId: 'com.isofttz.kanisaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHPgIOjsLJEvmCn2xB1Megy8VxdAphjPs',
    appId: '1:376704236556:web:4551a3a90928f79b924229',
    messagingSenderId: '376704236556',
    projectId: 'kkkt-miyuji',
    authDomain: 'kkkt-miyuji.firebaseapp.com',
    databaseURL: 'https://kkkt-miyuji-default-rtdb.firebaseio.com',
    storageBucket: 'kkkt-miyuji.firebasestorage.app',
    measurementId: 'G-KH8WH73L2T',
  );
}
